config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  root 'login#index'
  
  get 'login/index'
  get 'register/index'

  resources :teams do
    resources :players
  end

end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record documentation
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/player.rb
# frozen_string_literal: true

# Player model documentation
class Player < ApplicationRecord
  belongs_to :team
  validates :name, presence: true, length: { minimum: 2 }
  # before_action :authenticate_user!, :except => [:show, :index]
end

app/models/team.rb
# frozen_string_literal: true

# Article model documentation
class Team < ApplicationRecord
  has_many :players, dependent: :destroy
  validates :name, presence: true, length: { minimum: 2 }
  accepts_nested_attributes_for :players
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController documentation
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
# frozen_string_literal: true

# LoginController documentation
class LoginController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

# Players Controller documentation
# User can add and delete players
class PlayersController < ApplicationController

  def show
    @team = Team.find(params[:id])
    @player = @team.players.find(params[:team_id])
  end

  def new
    @team = Team.find(params[:id])
    @player = @team.player.new
  end

  def edit
    @team = Team.find(params[:id])
    @player = Player.find(params[:team_id])
  end

  def create
    @team = Team.find(params[:team_id])
    @player = @team.players.create(player_params)
    redirect_to @team
  end

  def update
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to @team
    else
      redirect_back(fallback_location: edit_team_player_path)
    end
  end

  def destroy
    @team = Team.find(params[:team_id])
    @player = @team.players.find(params[:id])
    @player.destroy
    redirect_to team_path(@team)
  end

  private

  def player_params
    params.require(:player).permit(:id, :name)
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to @team
    else
      render 'new'
    end
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to @team
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_bs_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #3364F6; border-radius: 0px;">
  <a class="navbar-brand" href="/">Team Creator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <div id="sign-in-status" class="navbar-text"></div>
      </li>
      <li class="nav-item">
        <button id="sign-in" class="btn btn-outline-light"></button>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="topbar">
  <nav class="navbar top-navbar navbar-expand-md navbar-dark">
      <div class="navbar-header">
          <!-- This is for the sidebar toggle which is visible on mobile only -->
          <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
          <!-- ============================================================== -->
          <!-- Logo -->
          <!-- ============================================================== -->
          <a class="navbar-brand" href="index.html">
              <b class="logo-icon">
                  <h2 style="color: black;">Team Creator</h2>
              </b>
          </a>
          <!-- ============================================================== -->
          <!-- Toggle which is visible on mobile only -->
          <!-- ============================================================== -->
          <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
      </div>
      <!-- ============================================================== -->
      <!-- End Logo -->
      <!-- ============================================================== -->
      <div class="navbar-collapse collapse" id="navbarSupportedContent">
          <!-- ============================================================== -->
          <!-- toggle and nav items -->
          <!-- ============================================================== -->
          <ul class="navbar-nav float-left mr-auto">
              <li class="nav-item d-none d-md-block">
              </li>
              <li class="nav-item dropdown">
              </li>
              <li class="nav-item">
              </li>
          </ul>
          <!-- ============================================================== -->
          <!-- Right side toggle and nav items -->
          <!-- ============================================================== -->
          <ul class="navbar-nav float-right">
              <li class="nav-item">
              </li>
              <li class="nav-item">
              </li>
              <li class="nav-item">
                  <div id="sign-in-status"></div>
              </li>
              <li class="nav-item">
                <button id="sign-in"></button>
              </li>
          </ul>
      </div>
  </nav>
</header>
<!-- ============================================================== -->
<!-- End Topbar header -->
<!-- ============================================================== -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #3364F6; border-radius: 0px;">
  <a class="navbar-brand" href="/">Team Creator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <div id="sign-in-status" class="navbar-text"></div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_sidenav.html.erb
<div class="col-sm-2 sidenav">
  <ul class="sidenav-list">
    <div class="authlinks">
      <li>
        <%= link_to 'All Teams', teams_path, :class => "btn btn-primary"%>
      </li>
      <li>
        <%= link_to 'Add Team', new_team_path, :class => "btn btn-primary"%>
      </li>
      <li class="nav-item">
        <button id="sign-in" class="btn btn-primary"></button>
      </li>
    </div>

  </ul>
</div>

<script>
firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    // User is signed in.
    console.log('Signed In');
    
  } else {
    // No user is signed in.
    console.log('Not Signed In');
    $('div.authlinks').hide();
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Rails default meta tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Firebase site auth and external scripts -->
    <meta name="google-site-verification" content="EV8XaWJLIAN4UWa0QCe9OOdr8iINFRMxk-yAxn6BCcc" />
    <script src="https://www.gstatic.com/firebasejs/5.5.6/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.5.3/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.5.3/firebase-auth.js"></script>
    <script src="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.js"></script>
    
    <!-- Firebase locally stored scripts -->
    <%= javascript_include_tag('config.js') %>
    <%= javascript_include_tag('firebase.js') %>

    <!-- Material Design Theming -->
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.orange-indigo.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    
    <!-- Firebase local and external css files -->
    <link type="text/scss" rel="stylesheet" src="/app/assets/stylesheets/firebase.scss" />
    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.css" />

    <!-- Rails default js and css link tags -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <title>Team Creator</title>
  </head>

  <body>

    <%= render partial: 'layouts/navbar' %>

    <div class="container-fluid text-center">    
      <div class="row content">
        <div class="col-sm-2 sidenav">
          <%= render partial: 'layouts/sidenav' %>
        </div>
        <div class="main col-sm-8 text-left">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/login/firebase_sample.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Email/Password Authentication Example</title>

  <!-- Material Design Theming (added) -->
  <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.orange-indigo.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

  <!-- Added to existing main.css -->
  <link rel="stylesheet" href="main.css">

  <!-- Import and configure the Firebase SDK -->
  <!-- These scripts are made available when the app is served or deployed on Firebase Hosting -->
  <!-- If you do not serve/host your project using Firebase Hosting see https://firebase.google.com/docs/web/setup (believe none of these are required as Babs has added required scripts - not sure about the last one - init.js)-->
  <script src="/__/firebase/5.5.5/firebase-app.js"></script>
  <script src="/__/firebase/5.5.5/firebase-auth.js"></script>
  <script src="/__/firebase/init.js"></script>
  
  <script type="text/javascript">
    /**
     * Handles the sign in button press.
     */
    function toggleSignIn() {
      if (firebase.auth().currentUser) {
        // [START signout]
        firebase.auth().signOut();
        // [END signout]
      } else {
        var email = document.getElementById('email').value;
        var password = document.getElementById('password').value;
        if (email.length < 4) {
          alert('Please enter an email address.');
          return;
        }
        if (password.length < 4) {
          alert('Please enter a password.');
          return;
        }
        // Sign in with email and pass.
        // [START authwithemail]
        firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
          // Handle Errors here.
          var errorCode = error.code;
          var errorMessage = error.message;
          // [START_EXCLUDE]
          if (errorCode === 'auth/wrong-password') {
            alert('Wrong password.');
          } else {
            alert(errorMessage);
          }
          console.log(error);
          document.getElementById('quickstart-sign-in').disabled = false;
          // [END_EXCLUDE]
        });
        // [END authwithemail]
      }
      document.getElementById('quickstart-sign-in').disabled = true;
    }
    /**
     * Handles the sign up button press.
     */
    function handleSignUp() {
      var email = document.getElementById('email').value;
      var password = document.getElementById('password').value;
      if (email.length < 4) {
        alert('Please enter an email address.');
        return;
      }
      if (password.length < 4) {
        alert('Please enter a password.');
        return;
      }
      // Sign in with email and pass.
      // [START createwithemail]
      firebase.auth().createUserWithEmailAndPassword(email, password).catch(function(error) {
        // Handle Errors here.
        var errorCode = error.code;
        var errorMessage = error.message;
        // [START_EXCLUDE]
        if (errorCode == 'auth/weak-password') {
          alert('The password is too weak.');
        } else {
          alert(errorMessage);
        }
        console.log(error);
        // [END_EXCLUDE]
      });
      // [END createwithemail]
    }
    /**
     * Sends an email verification to the user.
     */
    function sendEmailVerification() {
      // [START sendemailverification]
      firebase.auth().currentUser.sendEmailVerification().then(function() {
        // Email Verification sent!
        // [START_EXCLUDE]
        alert('Email Verification Sent!');
        // [END_EXCLUDE]
      });
      // [END sendemailverification]
    }
    function sendPasswordReset() {
      var email = document.getElementById('email').value;
      // [START sendpasswordemail]
      firebase.auth().sendPasswordResetEmail(email).then(function() {
        // Password Reset Email Sent!
        // [START_EXCLUDE]
        alert('Password Reset Email Sent!');
        // [END_EXCLUDE]
      }).catch(function(error) {
        // Handle Errors here.
        var errorCode = error.code;
        var errorMessage = error.message;
        // [START_EXCLUDE]
        if (errorCode == 'auth/invalid-email') {
          alert(errorMessage);
        } else if (errorCode == 'auth/user-not-found') {
          alert(errorMessage);
        }
        console.log(error);
        // [END_EXCLUDE]
      });
      // [END sendpasswordemail];
    }
    /**
     * initApp handles setting up UI event listeners and registering Firebase auth listeners:
     *  - firebase.auth().onAuthStateChanged: This listener is called when the user is signed in or
     *    out, and that is where we update the UI.
     */
    function initApp() {
      // Listening for auth state changes.
      // [START authstatelistener]
      firebase.auth().onAuthStateChanged(function(user) {
        // [START_EXCLUDE silent]
        document.getElementById('quickstart-verify-email').disabled = true;
        // [END_EXCLUDE]
        if (user) {
          // User is signed in.
          var displayName = user.displayName;
          var email = user.email;
          var emailVerified = user.emailVerified;
          var photoURL = user.photoURL;
          var isAnonymous = user.isAnonymous;
          var uid = user.uid;
          var providerData = user.providerData;
          // [START_EXCLUDE]
          document.getElementById('quickstart-sign-in-status').textContent = 'Signed in';
          document.getElementById('quickstart-sign-in').textContent = 'Sign out';
          document.getElementById('quickstart-account-details').textContent = JSON.stringify(user, null, '  ');
          if (!emailVerified) {
            document.getElementById('quickstart-verify-email').disabled = false;
          }
          // [END_EXCLUDE]
        } else {
          // User is signed out.
          // [START_EXCLUDE]
          document.getElementById('quickstart-sign-in-status').textContent = 'Signed out';
          document.getElementById('quickstart-sign-in').textContent = 'Sign in';
          document.getElementById('quickstart-account-details').textContent = 'null';
          // [END_EXCLUDE]
        }
        // [START_EXCLUDE silent]
        document.getElementById('quickstart-sign-in').disabled = false;
        // [END_EXCLUDE]
      });
      // [END authstatelistener]
      document.getElementById('quickstart-sign-in').addEventListener('click', toggleSignIn, false);
      document.getElementById('quickstart-sign-up').addEventListener('click', handleSignUp, false);
      document.getElementById('quickstart-verify-email').addEventListener('click', sendEmailVerification, false);
      document.getElementById('quickstart-password-reset').addEventListener('click', sendPasswordReset, false);
    }
    window.onload = function() {
      initApp();
    };
  </script>
</head>
<body>
<div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-header">

  <!-- Header section containing title -->
  <header class="mdl-layout__header mdl-color-text--white mdl-color--light-blue-700">
    <div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-grid">
      <div class="mdl-layout__header-row mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--8-col-desktop">
        <a href="/"><h3>Firebase Authentication</h3></a>
      </div>
    </div>
  </header>

  <main class="mdl-layout__content mdl-color--grey-100">
    <div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-grid">

      <!-- Container for the demo -->
      <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop">
        <div class="mdl-card__title mdl-color--light-blue-600 mdl-color-text--white">
          <h2 class="mdl-card__title-text">Firebase Email &amp; Password Authentication</h2>
        </div>
        <div class="mdl-card__supporting-text mdl-color-text--grey-600">
          <p>Enter an email and password below and either sign in to an existing account or sign up</p>

          <input class="mdl-textfield__input" style="display:inline;width:auto;" type="text" id="email" name="email" placeholder="Email"/>
          &nbsp;&nbsp;&nbsp;
          <input class="mdl-textfield__input" style="display:inline;width:auto;" type="password" id="password" name="password" placeholder="Password"/>
          <br/><br/>
          <button disabled class="mdl-button mdl-js-button mdl-button--raised" id="quickstart-sign-in" name="signin">Sign In</button>
          &nbsp;&nbsp;&nbsp;
          <button class="mdl-button mdl-js-button mdl-button--raised" id="quickstart-sign-up" name="signup">Sign Up</button>
          &nbsp;&nbsp;&nbsp;
          <button class="mdl-button mdl-js-button mdl-button--raised" disabled id="quickstart-verify-email" name="verify-email">Send Email Verification</button>
          &nbsp;&nbsp;&nbsp;
          <button class="mdl-button mdl-js-button mdl-button--raised" id="quickstart-password-reset" name="verify-email">Send Password Reset Email</button>

          <!-- Container where we'll display the user details -->
          <div class="quickstart-user-details-container">
            Firebase sign-in status: <span id="quickstart-sign-in-status">Unknown</span>
            <div>Firebase auth <code>currentUser</code> object value:</div>
            <pre><code id="quickstart-account-details">null</code></pre>
          </div>
        </div>
      </div>

    </div>
  </main>
</div>
</body>
</html>

app/views/login/index.html.erb
<h1 class="login-register-header">Log In to Team Creator</h1>
<div id="firebaseui-auth-container"></div>
<div id="register">
  <%= link_to 'Sign Up to Team Creator', register_index_path %>
<div>

app/views/players/_edit_form.html.erb
<%= form_for([ @team, @player ]) do |form| %>
 
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@player.errors.count, "error") %> prohibited
        this player from being saved:
      </h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, placeholder: @player.name %>
  </p>

  <p>
    <%= form.submit 'Submit', :class => "btn btn-primary" %>
  </p>
 
<% end %>

app/views/players/_form.html.erb
<%= form_with(model: [ @team, @team.players.build ]) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit 'Add New Player', :class => "btn btn-primary" %>
  </p>
<% end %>

app/views/players/_player.html.erb
<p>
  <%= player.name %>
</p>
<p>
  <%= link_to 'Destroy Comment', [player.team, player],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/players/edit.html.erb
<h1>Edit Player</h1>
 
<%= render 'edit_form' %>
 
<%= link_to 'Back', :back %>

app/views/players/show.html.erb
<h2>Player: <%= @player.name %></h2>
<br>


<p>Name: <%= @player.name %></p>
<p>Date Added: <%= @player.created_at %></p>
<p>Date Last Edited: <%= @player.updated_at %></p>
                           
<br>
<%= link_to 'Back', :back %>

app/views/register/index.html.erb
<h1 class="login-register-header">Sign Up to Team Creator</h1>
<div id="firebaseui-auth-container"></div>

app/views/user/index.html.erb
<h1 class="welcome-header">Welcome to Team Creator</h1>
<div id="firebaseui-auth-container"></div>